### ISSUE TITLE
Résolution portée des variables

### ISSUE THREAD

**Issue by M4p4ch3** [heptastique/PLD_COMP#29]

**Comment by M4p4ch3** [comment]
J'ai commencé à réfléchir et travailler la dessus sur mon repo de test (problème avec make, voir Discord)

Pour le moment, j'ai ajouté une liste de déclarations à l'objet bloc, qui contient donc la liste des variables qu'il "connait"
A chaque déclaration de variable dans un bloc, je l'ajoute à la liste
Pour les paramètres, on devrait pouvoir faire pareil

Qu'en pensez vous @AmosTrask @Rathkori @lulucasono ?

**Comment by AmosTrask** [comment]
Bloc contient aussi une liste d'instruction (les déclarations étant des instructions), ça va faire un peu redondant ? Est-ce qu'on retire l'héritage d'instruction pour déclaration ?

**Comment by M4p4ch3** [comment]
Oui en effet, ca ajoute un peu de redondance, on peut mettre dans la Declaration le Bloc auquel elle appartient ...
Actuellement l'héritage est super utile, puisqu'il suffit de faire : 
if (Instruction i est une Declaration)
